### ISSUE TITLE
Error generating commit

### ISSUE THREAD

**Issue by Loule95450** [clianor/ollama-commit#1]
Hello, running ollama-commit I have this error (I re-tried several times and still the same thing)

loule@Louis-MBP Application % ollama-commit
ℹ AI PROVIDER: ollama                                                                                                                                                      
ℹ AI MODEL: mistral                                                                                                                                                        
ℹ API HOST: http://localhost:11434                                                                                                                                         
ℹ LANGUAGE: en                                                                                                                                                             
◐ The currently prepared commit diff is 11,548 characters long.                                                                                                             
◐ Generating commit message...                                                                                                                                              

 ERROR  Cannot read properties of undefined (reading 'replaceAll')                                                                                                          

  at /opt/homebrew/lib/node_modules/ollama-commit/dist/index.cjs:2:1181
  at Array.map (<anonymous>)
  at _ (/opt/homebrew/lib/node_modules/ollama-commit/dist/index.cjs:2:1172)
  at async U (/opt/homebrew/lib/node_modules/ollama-commit/dist/index.cjs:18:57)

**Comment by clianor** [comment]
@Loule95450 

sorry.
It seems like the commit unit is too large and the commits are not being created properly.
Errors related to the code will be fixed with more detailed errors in the near future.
Could you try writing a smaller commit?

**Comment by Loule95450** [comment]
Hi ! I’ve made an update in the getDiff function by modifying the git command to exclude the ‘bun.lock’ file. This change ensures that the diff output is not included when generating a commit message. 
#2

**Comment by clianor** [comment]
@Loule95450 

Thank you for your contribution.
This content has been reflected.
thank you
