### ISSUE TITLE
ERROR  Unexpected end of JSON input

### ISSUE THREAD

**Issue by LalaDK** [clianor/ollama-commit#4]
Hello.

I'd like to try out your tool, but I get this error message:

```shell
❯ ollama-commit
ℹ AI PROVIDER: ollama
ℹ AI MODEL: mistral
ℹ API HOST: http://localhost:11434
ℹ LANGUAGE: en
◐ The currently prepared commit diff is 606 characters long.
◐ Generating commit message...


 ERROR  Unexpected end of JSON input

  at JSON.parse (<anonymous>)
  at _ (/Users/mads/.asdf/installs/nodejs/22.6.0/lib/node_modules/ollama-commit/dist/index.cjs:2:1110)
  at async U (/Users/mads/.asdf/installs/nodejs/22.6.0/lib/node_modules/ollama-commit/dist/index.cjs:18:57)
```

I've tried with different changes, but I still get the error.

**Comment by Mikaleb** [comment]
Same here

**Comment by Naimul007A** [comment]
make sure you have  AI MODEL: mistral in your  local.Coz ollama-commit use by default  mistral Model.
``
run llama run mistral
``

**Comment by clianor** [comment]
Hello,

It seems that the issue is caused by the ai model not responding in a fixed json format.

We are planning to introduce Structured Output to solve this issue.

Thank you.

**Comment by clianor** [comment]
Unfortunately, due to my personal schedule, I will not be able to work quickly.
